"""
This file is automatically generated by autosetup.py
Please edit the marked area only. Other areas will be
overwritten when autosetup is reruns.
"""

from setuptools import setup

params = dict(
    name='maskmm',
    description='pytorch-mask-rcnn',
    version='0.0.0',
    url='https://github.com/simonm3/maskmm.git',
    install_requires=['Pillow', 'PyYAML', 'analysis', 'cffi', 'h5py', 'ipython', 'matplotlib',
                      'numpy', 'pandas', 'pycocotools', 'scikit_image', 'scipy', 'skimage', 'torch', 'tqdm'],
    packages=['maskmm', 'maskmm.datagen', 'maskmm.datasets', 'maskmm.filters', 'maskmm.lib', 'maskmm.models', 'maskmm.utils', 'maskmm.datasets.coco', 'maskmm.datasets.nuke', 'maskmm.lib.nms',
              'maskmm.lib.roialign', 'maskmm.lib.nms._ext', 'maskmm.lib.nms._ext.nms', 'maskmm.lib.roialign.roi_align', 'maskmm.lib.roialign.roi_align._ext', 'maskmm.lib.roialign.roi_align._ext.crop_and_resize'],
    data_files=[('./etc/maskmm', ['.gitignore', 'LICENSE', 'README.md'])],
    py_modules=[],
    include_package_data=True,
    scripts=[])

########## EDIT BELOW THIS LINE ONLY ##########

params["install_requires"].remove("skimage")

########## EDIT ABOVE THIS LINE ONLY ##########

setup(**params)
