"""
This file is automatically generated by autosetup.py
Please edit the marked area only. Other areas will be
overwritten when autosetup is reruns.
"""

from setuptools import setup

params = dict(
    name='maskr',
    description='Pytorch MaskRCNN',
    version='0.0.0',
    url='https://github.com/simonm3/maskmm.git',
    install_requires=['Pillow', 'PyYAML', 'fastai', 'h5py', 'ipython', 'matplotlib', 'model', 'mrcnn',
                      'numpy', 'pandas', 'pycocotools', 'pytest', 'scikit_image', 'scipy', 'skimage', 'tensorflow', 'torch'],
    packages=['maskr', 'maskr.datagen', 'maskr.filters', 'maskr.lib', 'maskr.models', 'maskr.samples', 'maskr.test', 'maskr.utils',
              'maskr.lib.nms', 'maskr.lib.roialign', 'maskr.lib.roialign.roi_align', 'maskr.samples.coco', 'maskr.samples.nuke', 'maskr.samples.shapes'],
    data_files=[('./etc/maskr', ['.gitignore', 'LICENSE',
                                 'maskr.graphml', 'maskr.jpg', 'README.md'])],
    py_modules=[],
    include_package_data=True,
    scripts=None)

########## EDIT BELOW THIS LINE ONLY ##########

# pipreqs adds in error
for x in ["skimage", "model", "mrcnn"]:
    params["install_requires"].remove(x)

# autocreate .py files for notebooks
params["install_requires"].append("jupytext")

# not needed
params["data_files"] = []

########## EDIT ABOVE THIS LINE ONLY ##########

setup(**params)
