"""
This file is automatically generated by autosetup.py
Please edit the marked area only. Other areas will be
overwritten when autosetup is reruns.
"""

from setuptools import setup

params = dict(
    name='maskr',
    description='pytorch-mask-rcnn',
    version='0.0.0',
    url='https://github.com/simonm3/maskr.git',
    install_requires=['PyYAML', 'analysis', 'fastai', 'ipython', 'matplotlib',
                      'numpy', 'pandas', 'pytest', 'scikit_image', 'scipy', 'skimage', 'tensorflow', 'torch'],
    packages=['maskr', 'maskr.datagen', 'maskr.filters', 'maskr.lib', 'maskr.models', 'maskr.samples', 'maskr.test', 'maskr.utils', 'maskr.lib.nms', 'maskr.lib.roialign', 'maskr.lib.nms._ext',
              'maskr.lib.nms._ext.nms', 'maskr.lib.roialign.roi_align', 'maskr.lib.roialign.roi_align._ext', 'maskr.lib.roialign.roi_align._ext.crop_and_resize', 'maskr.samples.nuke'],
    data_files=[
        ('./etc/maskr', ['.gitignore', 'LICENSE', 'notes.txt', 'README.md'])],
    py_modules=[],
    include_package_data=True,
    scripts=None)

########## EDIT BELOW THIS LINE ONLY ##########

params["install_requires"].remove("skimage")

########## EDIT ABOVE THIS LINE ONLY ##########

setup(**params)
