"""
This file is automatically generated by autosetup.py
Please edit the marked area only. Other areas will be
overwritten when autosetup is reruns.
"""

from setuptools import setup

params = dict(
    name='nms',
    description='nms',
    version='0.0.0',
    url='https://github.com/simonm3/maskmm.git',
    install_requires=['numpy', 'torch'],
    packages=['_ext.nms'],
    data_files=[('./etc/nms', [])],
    py_modules=[],
    include_package_data=True,
    scripts=None)

########## EDIT BELOW THIS LINE ONLY ##########


########## EDIT ABOVE THIS LINE ONLY ##########

setup(**params)
